name: Daily Poetry Email
on:
  schedule:
    - cron: '0 13 * * *'  # Runs 9:00 UTC daily
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python logan-2025.py
        env:
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}

